### ISSUE TITLE
1.1D tx ptt problem

### ISSUE THREAD

**Issue by TA1FM** [nakhonthai/ESP32IGate#12]
I was using v0.9, I installed v1.1D, the TX LED does not light up and it does not switch the radio to TX. There was no such problem in v0.9.

**Comment by cabralcr** [comment]
Here the ptt is working normally

**Comment by nakhonthai** [comment]
Check in MOD Tab of GPIO and active pinout.

**Comment by TA1FM** [comment]
I made the esp32 igate circuit in v08, I connected it to an external handheld radio, I did not use a module like SA668, tx led and ptt were working fine, when I installed v1.1D on the same system, tx led and ptt did not work.
Even though I made the PTT GPIO settings in the MOD tab in the interface, it does not work. I tried many of the settings in the RADIO tab, but it still did not work. I could not figure out why. When I go back to the old v08 or v09 software, it works without any problems.
I follow your work with pleasure, thank you for your interest.
TA1FM
![ESP32DR_SimpleCircuit](https://github.com/nakhonthai/ESP32IGate/assets/117156073/fe876e7a-66d2-4aca-b76e-4719c01e7b00)

**Comment by nakhonthai** [comment]
If SQL pin signal not used, it to  fix  SQL  GPIO = -1

**Comment by TA1FM** [comment]
I'm sorry to take your valuable time, but when I set SQL GPIO to "-1", esp32 keeps resetting during TX.
https://photos.app.goo.gl/8rRFmnzmNKU61nzv5

**Comment by nakhonthai** [comment]
I've fixed this in the version 1.2b, please update firmware again.

**Comment by TA1FM** [comment]
I installed V1.2b, but during TX, ESP resets again. If I turn off the INET2RF switch, there is no problem as only igate.

**Comment by TA1FM** [comment]
There is no problem in the software without an OLED screen, but in the software with an OLED screen, the problem was solved when I added 2 pull-up 4k7 resistors to the data paths of the screen.
