### ISSUE TITLE
Feature Request: daughter card or optional space for an sa818

### ISSUE THREAD

**Issue by derekmurawsky** [nakhonthai/ESP32IGate#5]
This is a great project. I think it would be awesome to extend the board or create a daughter card for it which could take an [SA818](https://www.nicerf.com/item/1w-embedded-walkie-talkie-module-sa818) (or similar) to make an all-in-one APRS digipeter/igate. I could also see a similar daughter card for a LoRa radio, which seems to be gaining popularity in amateur radio circles. 
I'd love to help with something like this, but my embedded hardware/software skills are limited. Happy to support with testing, though.

**Comment by nakhonthai** [comment]
I'm thinking of creating a new project ESP32APRS for All-in-One.

**Comment by derekmurawsky** [comment]
I'd be happy to provide input and testing... Even code, though I'm not the best there. I believe there is a need for a true, simple, open source hardware APRS tracker/digi/igate and I suspect the esp32 would be able to handle it all.

**Comment by erstec** [comment]
> I'd be happy to provide input and testing... Even code, though I'm not the best there. I believe there is a need for a true, simple, open source hardware APRS tracker/digi/igate and I suspect the esp32 would be able to handle it all.

Ir handles already, several devices are constantly online with ESP32 for last year+ https://github.com/erstec/APRS-ESP
More, it have official APRS TOCALL

**Comment by nakhonthai** [comment]
I'm update in the Version 1.0 ,you can add and mod GPIO of RF Modules.

**Comment by derekmurawsky** [comment]
Awesome!
