### ISSUE TITLE
Add bluetooth TNC KISS to work with APRSdroid

### ISSUE THREAD

**Issue by ranaud80** [nakhonthai/ESP32IGate#9]
Hello,

is it  possible to add Bluetooth tnc kiss feature to be able to connect APRSdroid for monitoring a map.

[APRSdroid TNC KISS](https://github.com/ge0rg/aprsdroid/wiki/Settings#bluetooth-tnc)

Thank's
73
Arnaud

**Comment by nakhonthai** [comment]
Can't use, I removed Bluetooth because it was using too much memory.
